title: Hanlu Ge
description: Personal site
theme: jekyll-theme-minimal

# Optional: Add navigation (Jekyll themes like Minimal will pick this up)
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
